app_name: "SkullKing"

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

firebase:
  credentials_path: $GOOGLE_APPLICATION_CREDENTIALS
