app_name: "SkullKing"

server:
  applicationConnectors:
    - type: http
      port: 8080
  requestLog:
    type: classic
    timeZone: UTC
    appenders:
      - type: console

logging:
  level: INFO

firebase:
  database_url: "${DATABASE_URL}"
  service_account:
    type: "${TYPE}"
    project_id: "${PROJECT_ID}"
    private_key_id: "${PRIVATE_KEY_ID}"
    private_key: "${PRIVATE_KEY}"
    client_email: "${CLIENT_EMAIL}"
    client_id: "${CLIENT_ID}"
    auth_uri: "${AUTH_URI}"
    token_uri: "${TOKEN_URI}"
    auth_provider_x509_cert_url: "${AUTH_PROVIDER_CERT_URL}"
    client_x509_cert_url: "${CLIENT_CERT_URL}"

postgres:
  jdbcUrl: "${HEROKU_POSTGRESQL_GOLD_URL}"
  ssl: true
